### ISSUE TITLE
Bug with evaluator (pytrec)

### ISSUE THREAD

**Issue by bpiwowar** [terrierteam/ir_measures#49]
Running twice an evaluator with metrics evaluated at different cut-offs changes the result (I tested with nDCG and AP), as in this code (observe that the second call returns :

```py
import ir_measures
from ir_measures import * # imports all supported measures, e.g., AP, nDCG, RR, P

qrels = {
    'Q0': {"D0": 0, "D1": 1},
    "Q1": {"D0": 0, "D3": 2},
    "Q2": {"D0": 1, "D3": 2},
}
run = {
    'Q0': {"D0": 1.2, "D1": 1.0},
    "Q1": {"D0": 2.4, "D3": 3.6},
    "Q2": {"D4": 2.4, "D10": 3.6}
}

evaluator = ir_measures.evaluator([nDCG @ 10, nDCG @ 20], qrels)

ndcg20_a = evaluator.calc_aggregate(run)[nDCG@20]
ndcg20_b = evaluator.calc_aggregate(run)[nDCG@20]

# Gives AssertionError: nDCG@20 values are different: 0.5436432511904858 vs 0.0
assert ndcg20_a == ndcg20_b, f"nDCG@20 values are different: {ndcg20_a} vs {ndcg20_b}"
```

The second run returns a value of 0 (but this does not happen if using only `nDCG@20` or another metric)

**Comment by seanmacavaney** [comment]
Hi @bpiwowar -- this is a bug that stems from a problem with pytrec_eval. We've fixed the issue on our fork of pytrec_eval, which can be installed via `pytrec-eval-terrier==0.5.4`

It looks like the main branch or `ir-measures` requires the newer version, but it hasn't made its way to pypi yet.

More info on the issue here: https://github.com/terrierteam/ir_measures/issues/42#issuecomment-1237454081

**Comment by bpiwowar** [comment]
OK this indeed fixes the issue, thanks

**Comment by bpiwowar** [comment]
Would it be possible to release a new version of ir-measures with the updated requirements?

**Comment by seanmacavaney** [comment]
Hey @bpiwowar - I pushed v0.3.3 to pypi, which should address this problem.

**Comment by bpiwowar** [comment]
Great thanks !
